version: '3.8'
services:
        ebook:
             build: .
             container_name: do-s2-managed-server-and-backend
             image: registry.mejik.xyz/ebook/do-s2-managed-server-and-backend
             ports:
                     - 3039:3000
